version: '3'

services:
  odoo-mbo15:
    # image: odoo-app
    build: 
      context: .
      dockerfile: Dockerfile.Python3.8
    container_name: odoo-mbo15
    networks:
      - odoo-nextjs_odoo-network
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    command: python /opt/odoo/core/odooce/odoo-bin -c /opt/odoo/config/odoo.conf
    volumes:
      - ./odoo-config:/opt/odoo/config
      - ./odoo-data:/opt/odoo/.local
      - ./extra-addons:/opt/odoo/extra-addons
    restart: always
networks:
  odoo-nextjs_odoo-network:
    external: true
